### ISSUE TITLE
Question: Is this sufficiently up to date with the python implementation?

### ISSUE THREAD

**Issue by KevinDanikowski** [jellydn/justext#5]
Thank you for making this package. Is this sufficiently up to date with the python implementation (https://github.com/miso-belica/jusText) ? Or was it a nearly identical replica at the time of this implementation?

**Comment by jellydn** [comment]
Hi @KevinDanikowski

```
 Or was it a nearly identical replica at the time of this implementation?
```

Correct. I haven't checked the Python implementation yet.
